### ISSUE TITLE
Roll out nightly and stable release packages

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/shark-ai#400]
### Target: this week (by Nov 1)

- [x] Land new versioning scheme in sharktank and shortfin: https://github.com/nod-ai/SHARK-Platform/pull/398
- [x] https://github.com/nod-ai/SHARK-Platform/issues/294 Build sharktank wheel and push to https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels
- [x] Remove old version scheme packages from https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels
- [x] Pick https://github.com/nod-ai/SHARK-Platform/pull/244 back up and land the meta package
- [x] Add instructions to README files for installing nightly releases https://github.com/nod-ai/SHARK-Platform/issues/359

This will get us `pip install shark-platform -f https://github.com/nod-ai/SHARK-Platform/releases/expanded_assets/dev-wheels`

### Target: next week (by Nov 8)

- [x] Roll out new versioning scheme and renamed packages in IREE: https://github.com/iree-org/iree/issues/18938
- [x] Point sharktank and shortfin at the newly renamed packages
- [x] Write scripts for promoting nightly releases to stable releases for pypi publishing (drop `candidate` / `rc` from names/versions)
- [x] Publish stable releases for all packages
- [x] User facing installation guide (repository root README, https://github.com/nod-ai/SHARK-Platform/issues/359)

This will get us `pip install shark-platform`

### Backlog

Wider support for Python versions

- [ ] https://github.com/iree-org/iree/issues/18652
- [ ] https://github.com/nod-ai/SHARK-Platform/issues/349

**Comment by ScottTodd** [comment]
Researching how to promote versions from dev/rc --> stable, without needing to rebuild wheels:

* https://www.pyopensci.org/python-package-guide/package-structure-code/python-package-versions.html
* https://hatch.pypa.io/latest/version/ (if we switch our build tool)
* https://pypi.org/project/change-wheel-version/ and https://github.com/hauntsaninja/change_wheel_version (could adapt/reference the source if the tool doesn't do everything we need)

**Comment by ScottTodd** [comment]
Nightly releases are now documented here: https://github.com/nod-ai/SHARK-Platform/blob/main/docs/nightly_releases.md

**Comment by ScottTodd** [comment]
We're making good progress on this.

Latest detailed task list (in order of rollout):

### Publish `iree-base-compiler` and `iree-base-runtime` version 2.9.0 to nightly and PyPI

Today

- [ ] Merge https://github.com/iree-org/iree/pull/19034
- [ ] Merge https://github.com/iree-org/iree/pull/19061
- [ ] Trigger IREE release of `iree-base-compiler` and `iree-base-runtime` version 2.9.0 using https://github.com/iree-org/iree/actions/workflows/oneshot_candidate_release.yml or wait for https://github.com/iree-org/iree/actions/workflows/schedule_candidate_release.yml
- [ ] Determine the process for updating the Python package versions for promotion from rc to stable version
- [ ] Promote release from one-shot or nightly to pypi using new package name

### Update downstream projects to new package names and versions

Late today / tomorrow

- [ ] https://github.com/iree-org/iree/pull/19065
- [ ] Point https://github.com/iree-org/iree-turbine version 2.9.0 at new package names
- [ ] Change https://github.com/nod-ai/SHARK-Platform version to 2.9.0 and delete existing 3.0.0 dev wheels
- [ ] Point https://github.com/nod-ai/SHARK-Platform at new package names
- [ ] Switch shortfin CMake project version to match Python package version: https://github.com/nod-ai/SHARK-Platform/blob/79fe7e2711ff6da3f66540da55cf160343917f9c/shortfin/CMakeLists.txt#L16-L19

### Complete the packaging for shark-platform

Late today / tomorrow

- [ ] Build shark-platform meta-package that pins explicit versions of `iree-turbine`, `iree-base-compiler`, and `iree-base-runtime`. Allow for patch versions to drift?
- [ ] Start publishing shark-platform meta-package to dev wheels (nightly)
- [ ] Fix sharktank install requirements to include packages needed for basic tasks (install, import, run sample code)
- [ ] Publish sharktank, shortfin, and shark-platform 2.9.0 packages to pypi

### Finish 3.0.0 release

Next week

- [ ] Update versions to 3.0.0 for candidate releases
- [ ] Wait for release branch cut
- [ ] Cut 3.0.0 releases for each package
- [ ] Push all packages to PyPI
- [ ] Finalize release notes and user documentation to use the PyPI packages

**Comment by ScottTodd** [comment]
I've been stuck all day trying to update iree-turbine to use the new iree-base-compiler and iree-base-runtime packages: https://github.com/iree-org/iree-turbine/pull/258. There are new test failures that look meaningful.

Without that change, the iree-turbine package will still depend on the old IREE package names, so users will download both `iree-compiler` and `iree-base-compiler` packages. That is already happening today in some workflows here, due to https://github.com/nod-ai/SHARK-Platform/pull/449.

We might actually be able to proceed with the redundant installs for a little bit, but I'm not sure what the implications will be.

**Comment by ScottTodd** [comment]
Figured out all the test failures and pushed iree-turbine 2.9.0:
* https://github.com/iree-org/iree-turbine/releases/tag/v2.9.0
* https://pypi.org/project/iree-turbine/2.9.0/

**Comment by ScottTodd** [comment]
I'm going to call it for the day. Next steps for Monday:

* Check https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels to see if the shortfin and sharktank rc wheels there are suitable for pushing to pypi
  * See if installing them pulls in iree-turbine, iree-base-compiler, and iree-base-runtime versions 2.9.0 from PyPI as expected
* Fork https://github.com/iree-org/iree/blob/main/build_tools/python_deploy/promote_whl_from_rc_to_final.py to https://github.com/nod-ai/SHARK-Platform/tree/main/build_tools
* Use that script to drop the `rcYYYYMMDD` part of the .whl files
* Upload the new wheel files to https://pypi.org/project/sharktank/ and https://pypi.org/project/shortfin/

Once we have that initially working, we can also add the shark-platform meta package that directly pins the versions of each package that we want, then do the same build -> publish to dev wheels -> push to pypi process for that package.

**Comment by ScottTodd** [comment]
Initial 2.9.0 releases of all packages have been published to PyPI. More work remains to get the process running smoothly, but we should have enough for testing using standard pip commands with no extra package index or source builds.

**Comment by ScottTodd** [comment]
Steps for 3.0.0 release next week:

- [ ] Complete IREE release after choosing a nightly to promote: https://github.com/iree-org/iree/issues/19063 
- [ ] Complete iree-turbine release by merging https://github.com/iree-org/iree-turbine/pull/275 and following https://github.com/iree-org/iree-turbine/blob/main/docs/releasing.md
- [ ] Merge https://github.com/nod-ai/shark-ai/pull/553
- [ ] Trigger a build of https://github.com/nod-ai/shark-ai/actions/workflows/build_packages.yml
- [ ] Run https://github.com/nod-ai/shark-ai/blob/main/build_tools/python_deploy/pypi_deploy.sh
- [ ] Copy release notes draft to https://github.com/nod-ai/shark-ai/releases/tag/v3.0.0 and adjust the git tag

**Comment by ScottTodd** [comment]
3.0.0 release is live. Calling this fixed.
