### ISSUE TITLE
Streamline LLM import/compile/serve user experience

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/shark-ai#691]
Here is our current documentation for running llama models through shark-ai: https://github.com/nod-ai/shark-ai/blob/main/docs/shortfin/llm/user/e2e_llama8b_mi300x.md ([permalink](https://github.com/nod-ai/shark-ai/blob/d279afff48c56ab5e0e6e5ebe2717ccf0b26ee50/docs/shortfin/llm/user/e2e_llama8b_mi300x.md)).

Our current steps are convoluted compared to similar documentation in other projects.

## Comparison with other projects

vLLM

* https://docs.vllm.ai/en/latest/getting_started/quickstart.html
* https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#example-of-usage-for-a-pair-of-a-string-and-a-list-of-texts

TensorRT-LLM

* https://nvidia.github.io/TensorRT-LLM/quick-start-guide.html
* https://nvidia.github.io/TensorRT-LLM/commands/trtllm-serve.html
* https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html 

MLC LLM

* https://llm.mlc.ai/docs/get_started/introduction.html
* https://llm.mlc.ai/docs/compilation/compile_models.html#clone-from-hf-and-convert-weight
* https://github.com/bentoml/BentoMLCLLM?tab=readme-ov-file#set-up-the-environment

Ollama

* https://github.com/ollama/ollama

TorchServe

* https://pytorch.org/serve/batch_inference_with_ts.html

## Feedback

I have some inlined comments on one file [in this commit on my fork](https://github.com/ScottTodd/shark-ai/commit/bfde15b423471b8d7d1db8d06686227af3899940). Here I'll try to summarize them as tasks:

- [ ] Only one line in that guide is actually device-specific: `--iree-hip-target=gfx942`. The file should be generalized.
- [ ] Any actions that create files (downloading, importing, compiling, etc.) should choose a consistent and structured default location. Similarly, tool arguments should have sensible default values, so the documentation does not need to specify 9+ environment variables
- [ ] The [`sharktank.utils.hf_datasets` module ](https://github.com/nod-ai/shark-ai/blob/main/sharktank/sharktank/utils/hf_datasets.py) is a tool for developer convenience and testing. Users should be directed to download from huggingface directly, using standard tools and APIs (e.g. the huggingface-cli tool or the hugging_face library)
  * We should refer to models with their standard "organization/repository" naming, not the shorthand from our `hf_datasets` file, e.g. `SanctumAI/Meta-Llama-3.1-8B-Instruct-GGUF` and not `llama3_8B_fp16`
- [ ] We could group some subsets of the [download, export to mlir, compile, serve] steps into a new tool, similar to how the projects linked above handle it. This could leverage `iree.build` for some or all steps: https://github.com/nod-ai/shark-ai/issues/402
  * Such a script could default to the current GPU device(s) and include options for multi-device sharding and other high level configurations that users/developers may want to use
- [ ] The golden path through the documentation should be free text like "if you see this error, run this to fix it" or "make sure you have these files here before running this command". The error messages should explain how to fix them and the defaults should work for most users.
- [ ] Our current server seems to have its own API? We should use industry standard APIs like OpenAI's API : https://github.com/nod-ai/shark-ai/issues/245
- [ ] Demo commands do not need to use a python interpreter to send HTTP requests. Other projects provide a client library or use `curl`.
- [ ] Server shutdown needs a better story than `kill -9 $shortfin_process`: https://github.com/nod-ai/shark-ai/issues/490

**Comment by ScottTodd** [comment]
I just went through the current docs at https://github.com/nod-ai/shark-ai/blob/main/docs/shortfin/llm/user/e2e_llama8b_mi300x.md. Good news - everything worked on this machine, using Python 3.11 on Ubuntu 22.04 and a w7900 (with `--iree-hip-target=gfx1100`)

A few more notes:

- [ ] Export failed on Python 3.10 with
    ```
      File "/home/nod/dev/projects/shark-ai/3.11.llama.venv/lib/python3.10/site-packages/sharktank/types/tensors.py", line 499
        self.as_torch()[*key] = unbox_tensor(value)
                        ^
    ```
    Docs already suggest 3.11 as the minimum, but we can do better.
- [ ] The environment variables, if we keep them, should put more context in the file names:
    ```diff
    -    export MLIR_PATH=$EXPORT_DIR/model.mlir
    -    export VMFB_PATH=$EXPORT_DIR/model.vmfb
    +    export MLIR_PATH=$EXPORT_DIR/llama_8b_fp16_bs1_bs4.mlir
    +    export VMFB_PATH=$EXPORT_DIR/llama_8b_fp16_bs1_bs4_rocm_gfx1100.vmfb
    ```

    Building tools to group the download/import/compile steps would help keep the names and metadata organized
- [ ] The `sharktank.examples.export_paged_llm_v1` script (I'd like to at least rename it...) has no progress indicators and takes around 1 minute for the provided 8b example on this machine. We could at least log some expectation about how long it will take, so users know how long to give it before giving up.
- [ ] As mentioned in some other points, Running the server with `python -m shortfin_apps.llm.server`, grabbing the process ID, and redirecting output to a file is awkward. We can add a console script entry point like `shortfin_server`, build logging redirection into the script itself, and add a better shutdown method
- [ ] The output for
    `payload = {"text": "Name the capital of the United States.", "sampling_params": {"max_completion_tokens": 50}}`
    is
    `data:  Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington, D.C.! Washington`
    on my machine. Should it be repeated that much?

**Comment by ScottTodd** [comment]
> [ ] Our current server seems to have its own API? We should use industry standard APIs like OpenAI's API : [[tracking] Production Grade Shortfin-LLM #245](https://github.com/nod-ai/shark-ai/issues/245)

Quoting https://sgl-project.github.io/frontend/frontend.html, 

> The frontend language can be used with local models or API models. It is an alternative to the OpenAI API. You may find it easier to use for complex prompting workflow.

We should be able to support both / multiple APIs, but focusing on SGLang for now makes sense.

**Comment by stbaione** [comment]
Idea for streamlining this process. I was thinking of moving it to the server command itself and adding a mutually exclusive list of args. Kinda like how [sglang](https://docs.sglang.ai/start/send_request.html#Launch-A-Server) does it.

For example:

```bash
python -m shortfin_apps.llm.server \
   --model-path https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct
   --device hip \
   --tp 8 \
   --compile-target gfx942 \
   --device_ids 0 1 2 3 4 5 6 7
```

We would default model artifacts to be saved to .cache/shark/Llama-3.1-405b-Instruct, and add an optional arg --cache-dir if they wanna save them somewhere else. Maybe we also include some flags for regenerating cached artifacts, like --ensure-export, --ensure-compile.

We would still wanna support the case of pre-compiled artifacts, so maybe we keep around our original set of args for that scenario:

```bash
python -m shortfin_apps.llm.server \
   --tokenizer_json /path/to/output/tokenizer.json \
   --model_config /path/to/output/llama3.1-405b.config.json \
   --vmfb /path/to/output/llama3.1-405b.vmfb \
   --parameters \
      /path/to/output/llama3.1-405b.irpa \
      /path/to/output/llama3.1-405b.rank0.irpa \
      /path/to/output/llama3.1-405b.rank1.irpa \
      /path/to/output/llama3.1-405b.rank2.irpa \
      /path/to/output/llama3.1-405b.rank3.irpa \
      /path/to/output/llama3.1-405b.rank4.irpa \
      /path/to/output/llama3.1-405b.rank5.irpa \
      /path/to/output/llama3.1-405b.rank6.irpa \
      /path/to/output/llama3.1-405b.rank7.irpa \
   --device=hip \
   --device_ids 0 1 2 3 4 5 6 7
```

**Comment by sogartar** [comment]
We can expand the interface of [BaseLayer](https://github.com/nod-ai/shark-ai/blob/bc765265590f5a2151daef184f7dcbcaa863907d/sharktank/sharktank/layers/base.py#L36) with methods like `export`.
I have already added [sample_inputs](https://github.com/nod-ai/shark-ai/blob/bc765265590f5a2151daef184f7dcbcaa863907d/sharktank/sharktank/layers/base.py#L109) there, which is an important element to allow for tracing trough the model during export.
The main point is once you have your model configured you are able to export and compile it. Then we can have presets for various sensible model configurations.

**Comment by sogartar** [comment]
I think we could also not be specific only to LLMs, but support one flow for all models.

**Comment by sogartar** [comment]
I will create a draft on making sharktank models configurable through a json config file. This config would have sufficient info to export and compile a model. Then users like shortfin can utilize this config.

**Comment by sogartar** [comment]
Here is a [change](https://github.com/nod-ai/shark-ai/pull/1013) that helps streamline sharktank model configuration, exporting and compilation.
